### ISSUE TITLE
Allow duplicated columns?

### ISSUE THREAD

**Issue by gacelita** [kishanov/re-frame-datatable#9]
Hi,

Right now I'm duplicating the id field in my data because I need it for two columns: the "actions" column, which contains buttons that trigger actions (who need to know the ID), and the "id" column, which simply shows the ID.

This is obviously ugly, is there a better way?

Thank you and great job

**Comment by kishanov** [comment]
Nothing prevents you from specifying non-existent `column-key` like `[:some-action]`. Not the most beautiful solution, so in the future version I might add a special keyword or make column-key optional.

**Comment by gacelita** [comment]
I used a non-existent key (:actions), and the second argument of the custom render function (the whole row) to access the ID.

Thanks!
